### ISSUE TITLE
Can't initialize with client object with 0.1.5

### ISSUE THREAD

**Issue by dplummer** [avvo/json_api_resource#4]
```
/Users/dplummer/.rvm/gems/ruby-2.2.0/gems/json_api_client-0.7.1/lib/json_api_client/helpers/attributable.rb:64:in `method_missing'
/Users/dplummer/.rvm/gems/ruby-2.2.0/gems/json_api_client-0.7.1/lib/json_api_client/helpers/linkable.rb:18:in `method_missing'
/Users/dplummer/.rvm/gems/ruby-2.2.0/gems/json_api_resource-0.1.5/lib/json_api_resource/resource.rb:41:in `attributes='
/Users/dplummer/.rvm/gems/ruby-2.2.0/gems/json_api_resource-0.1.5/lib/json_api_resource/resource.rb:23:in `initialize'
/Users/dplummer/src/billboard/app/models/gnomon/location.rb:28:in `new'
/Users/dplummer/src/billboard/app/models/gnomon/location.rb:28:in `block in find_by_ip_address'
/Users/dplummer/src/billboard/app/models/gnomon/location.rb:27:in `map!'
/Users/dplummer/src/billboard/app/models/gnomon/location.rb:27:in `find_by_ip_address'
/Users/dplummer/src/billboard/app/helpers/geo_ip_helper.rb:5:in `block in geo_ip_lookup'
/Users/dplummer/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/cache.rb:299:in `block in fetch'
/Users/dplummer/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/cache.rb:585:in `block in save_block_result_to_cache'
/Users/dplummer/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/cache.rb:547:in `block in instrument'
/Users/dplummer/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
/Users/dplummer/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/cache.rb:547:in `instrument'
/Users/dplummer/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/cache.rb:584:in `save_block_result_to_cache'
/Users/dplummer/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/cache.rb:299:in `fetch'
/Users/dplummer/src/billboard/app/helpers/geo_ip_helper.rb:4:in `geo_ip_lookup'
/Users/dplummer/src/billboard/app/helpers/geo_ip_helper.rb:21:in `geo_ip_override'
/Users/dplummer/src/billboard/app/helpers/geo_ip_helper.rb:11:in `geo_ip_location'
test/helpers/geo_ip_helper_test.rb:18:in `block in <class:GeoIpHelperTest>'
```

From this code:

``` ruby
 class Gnomon::Location < JsonApiResource::Resource
   self.client_klass = Gnomon::Client::Location

    def self.find_by_ip_address(params = {})
      client_klass.find_by_ip_address(params).map! do |result|
        Gnomon::Location.new(result)
      end
    end
end
```

**Comment by dplummer** [comment]
I think I can just change the use to be `Gnomon::Location.new(client: result)`
